bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '100000': 'R100,000',
    '200000': 'R200,000',
    '300000': 'R300,000',
    '400000': 'R400,000',
    '500000': 'R500,000',
    '600000': 'R600,000',
    '700000': 'R700,000',
    '800000': 'R800,000',
    '900000': 'R900,000',
    '10000000': 'R1,000,000'
}

state_choices = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AS': 'American Samoa',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN':  'Indiana',
    'KS':  'Kansas',
    'KY':  'Kentucky',
    'LA':  'Louisiana',
    'ME':  'Maine',
    'MD':  'Maryland',
    'MA': 'Massachusetts',
    'MI':  'Michigan',
    'MN':  'Minnesota',
    'MS':  'Mississippi',
    'MO':  'Missouri',
    'MT':  'Montana',
    'NE':  'Nebraska',
    'NV':  'Nevada',
    'NH':  'New Hampshire',
    'NJ': ' New Jersey',
    'NM':  'New Mexico',
    'NY':  'New York',
    'NC':  'North Carolina',
    'ND':  'North Dakota ',
    'OH':  'Ohio ',
    'OK':  'Oklahoma',
    'OR':  'Oregon',
    'PA':  'Pennsylvania',
    'RI': 'Rhode Island',
    'SC':  'South Carolina',
    'SD': 'South Dakota',
    'TN':  'Tennessee',
    'TX':  'Texas',
    'UT':  'Utah',
    'VT':  'Vermont ',
    'VA':  'Virginia',
    'WA':  'Washington',
    'WV':  'West Virginia',
    'WI':  'Wisconsin',
    'WY':  'Wyoming',
}
